# Info at https://images.webofknowledge.com/images/help/WOS/hs_wos_fieldtags.html
diz= {
    'AU' : 'Authors',
    'XXX' : 'Author(s) ID',
    'TI' : 'Title',
    'PY' : 'Year',
    'XXX' : 'Source title',
    'XXX' : 'Volume',
    'XXX' : 'Issue',
    'XXX' : 'Art. No.',
    'XXX' : 'Page start',
    'XXX' : 'Page end',
    'XXX' : 'Page count',
    'XXX' : 'Cited by',
    'XXX' : 'DOI',
    'XXX' : 'Link',
    'XXX' : 'Affiliations',
    'XXX' : 'Authors with affiliations',
    'XXX' : 'Abstract',
    'XXX' : 'Chemicals/CAS',
    'XXX' : 'Tradenames',
    'XXX' : 'Manufacturers',
    'XXX' : 'Funding Details',
    'XXX' : 'Funding Text 1',
    'XXX' : 'Funding Text 2',
    'XXX' : 'References',
    'XXX' : 'Correspondence Address',
    'XXX' : 'Editors',
    'XXX' : 'Sponsors',
    'XXX' : 'Publisher',
    'XXX' : 'Conference name',
    'XXX' : 'Conference date',
    'XXX' : 'Conference location',
    'XXX' : 'Conference code',
    'XXX' : 'ISSN',
    'XXX' : 'ISBN',
    'XXX' : 'CODEN',
    'XXX' : 'PubMed ID',
    'XXX' : 'Language of Original Document',
    'XXX' : 'Abbreviated Source Title',
    'XXX' : 'Document Type',
    'XXX' : 'Publication Stage',
    'XXX' : 'Access Type',
    'XXX' : 'Source',
    'XXX' : 'EID'
}

print(diz)