# Info at https://images.webofknowledge.com/images/help/WOS/hs_wos_fieldtags.html
diz= {
    'AU' : 'Authors',
    'TI' : 'Title',
    'PY' : 'Year',
    'SO' : 'Source title',
    'VL' : 'Volume',
    'IS' : 'Issue',
    'AR' : 'Art. No.',
    'BP' : 'Page start',
    'EP' : 'Page end',
    'PG' : 'Page count',
    'DI' : 'DOI',
    'AB' : 'Abstract',
    'BE' : 'Editors',
    'PU' : 'Publisher',
    'CT' : 'Conference name',
    'CY' : 'Conference date',
    'CL' : 'Conference location',
    'SN' : 'ISSN',
    'BN' : 'ISBN',
    'PM' : 'PubMed ID',
    'LA' : 'Language of Original Document',
    'J9' : 'Abbreviated Source Title',
    'DT' : 'Document Type',
    'OA' : 'Access Type', 
    'FU' : 'Funding Details',
    
}

# diz= {
#     'AU' : 'Authors',
#     'XXX' : 'Author(s) ID',
#     'TI' : 'Title',
#     'PY' : 'Year',
#     'SO' : 'Source title',
#     'VL' : 'Volume',
#     'IS' : 'Issue',
#     'AR' : 'Art. No.',
#     'BP' : 'Page start',
#     'EP' : 'Page end',
#     'PG' : 'Page count',
#     'XXX' : 'Cited by',
#     'DI' : 'DOI',
#     'XXX' : 'Link',
#     'XXX' : 'Affiliations',
#     'XXX' : 'Authors with affiliations',
#     'AB' : 'Abstract',
#     'XXX' : 'Chemicals/CAS',
#     'XXX' : 'Tradenames',
#     'XXX' : 'Manufacturers',
#     'XXX' : 'Funding Details',
#     'XXX' : 'Funding Text 1',
#     'XXX' : 'Funding Text 2',
#     'XXX' : 'References',
#     'XXX' : 'Correspondence Address',
#     'BE' : 'Editors',
#     'XXX' : 'Sponsors',
#     'PU' : 'Publisher',
#     'CT' : 'Conference name',
#     'CY' : 'Conference date',
#     'CL' : 'Conference location',
#     'XXX' : 'Conference code',
#     'SN' : 'ISSN',
#     'BN' : 'ISBN',
#     'XXX' : 'CODEN', # N
#     'PM' : 'PubMed ID',
#     'LA' : 'Language of Original Document',
#     'J9' : 'Abbreviated Source Title',
#     'DT' : 'Document Type',
#     'XXX' : 'Publication Stage',
#     'OA' : 'Access Type', 
#     'XXX' : 'Source', # N
#     'XXX' : 'EID' # N
# }